SELECT
    A.COB_DATE,
    A.POSITION_ULT_ISSUER_PARTY_DARWIN_NAME,
    A.RATING2,
    ABS (SUM (A.USD_PV10_BENCH)) AS ABS_USD_PV10_BENCH,
    ABS (SUM (A.USD_PV01SPRD)) AS ABS_USD_PV01SPRD
FROM cdwuser.U_DM_CC A
WHERE
    A.COB_DATE in ('2018-02-28','2018-02-27')
    AND A.CREDIT_CORPS_CCC_BUSINESS_AREA IN ('CREDIT-CORPORATES')
    AND A.CREDIT_TRADING_FLAG = 'Junior Subs'
GROUP BY
    A.COB_DATE, 
    A.POSITION_ULT_ISSUER_PARTY_DARWIN_NAME,
    A.RATING2