SELECT
    A.COB_DATE,
    A.CCC_BUSINESS_AREA,
    a.RATING_B, 
    A.TERM_OF_POSITION_BUCKETED,
    SUM (A.USD_PV01SPRD) AS USD_PV01SPRD
FROM cdwuser.U_DM_CC A
WHERE
    A.COB_DATE IN ('2018-02-28') AND 
    A.CCC_BUSINESS_AREA = 'DSP - CREDIT'
GROUP BY
    A.COB_DATE,
    A.CCC_BUSINESS_AREA,
    a.RATING_B, 
    A.TERM_OF_POSITION_BUCKETED