SELECT
    a.POSITION_ULT_ISSUER_PARTY_DARWIN_NAME,
    a.COB_DATE,
    SUM (A.USD_NET_EXPOSURE) AS USD_NET_EXPOSURE
FROM cdwuser.U_DM_CC A
WHERE
    a.COB_DATE IN ('2018-02-28') AND 
    a.CCC_BUSINESS_AREA = 'MUNICIPAL SECURITIES' AND
    a.PRODUCT_TYPE_CODE = 'BANKDEBT'
GROUP BY
    a.COB_DATE,
    a.POSITION_ULT_ISSUER_PARTY_DARWIN_NAME