SELECT
    A.COB_DATE,
    A.CCC_BUSINESS_AREA,
    A.PRODUCT_TYPE_CODE_GROUPED,
    SUM (A.USD_PV10_BENCH) AS USD_PV10_BENCH
FROM cdwuser.U_DM_CC A
WHERE
    A.COB_DATE IN ('2018-02-28') AND 
    A.CCC_BUSINESS_AREA = 'DSP - CREDIT'
GROUP BY
    A.COB_DATE,
    A.CCC_BUSINESS_AREA,
    A.PRODUCT_TYPE_CODE_GROUPED