Select 
COB_DATE,
Case When FID1_INDEX_FAMILY = 'UNDEFINED' Then 'BESPOKE INDEX'
Else FID1_INDEX_FAMILY End as INDEX_FAMILY,
sum(Coalesce(USD_INDEX_PV01,0)) INDEX_BASIS_01
from cdwuser.U_IR_MSR a
where
    A.COB_DATE in ('2018-02-28','2018-02-27')
    and CCC_BUSINESS_AREA = 'DSP - CREDIT'
Group by
COB_DATE, 
Case When FID1_INDEX_FAMILY = 'UNDEFINED' Then 'BESPOKE INDEX'
Else FID1_INDEX_FAMILY End
Having sum(Coalesce(USD_INDEX_PV01,0)) != 0