SELECT
    A.COB_DATE,
    A.CREDIT_CORPS_CCC_BUSINESS_AREA,
    A.CCC_PRODUCT_LINE,
    A.RATING_B,
    A.TERM_OF_POSITION_BUCKETED,
    SUM (A.USD_PV01SPRD) AS USD_PV01SPRD
FROM cdwuser.U_DM_CC A
WHERE
    A.COB_DATE IN ('2018-02-28') AND 
    A.CCC_PRODUCT_LINE = 'DISTRESSED TRADING' 
GROUP BY
    A.COB_DATE,
    A.CREDIT_CORPS_CCC_BUSINESS_AREA,
    A.CCC_PRODUCT_LINE,
    A.RATING_B,
    A.TERM_OF_POSITION_BUCKETED