Select COB_DATE , CCC_PL_REPORTING_REGION , CCC_DIVISION , CCC_BUSINESS_AREA ,LE_GROUP, CCC_STRATEGY , CCC_BANKING_TRADING , CCC_PRODUCT_LINE , PRODUCT_TYPE_CODE , MEASURE_CURRENCY_CCY1 , HEDGE_STRATEGY , TERM_BUCKET , ONSHORE_FL , BOOK , BU_RISK_SYSTEM  , sum( coalesce(USD_FX,0) ) as Total_USD_FX From cdwuser.U_FX_MSR a  


WHERE COB_DATE in ('2018-02-28','2018-02-21')
AND a.CCC_BANKING_TRADING = 'TRADING'
    AND CCC_DIVISION NOT IN ('FID DVA', 'FIC DVA')  AND CCC_STRATEGY NOT IN ('MS DVA STR NOTES IED')

and CCC_DIVISION in ('FIXED INCOME DIVISION')     and MEASURE_CURRENCY_CCY1 in ('CNY', 'CNH')     Group by COB_DATE , CCC_PL_REPORTING_REGION , CCC_DIVISION , CCC_BUSINESS_AREA , CCC_STRATEGY , CCC_BANKING_TRADING , CCC_PRODUCT_LINE , PRODUCT_TYPE_CODE , MEASURE_CURRENCY_CCY1 ,LE_GROUP, HEDGE_STRATEGY , TERM_BUCKET , ONSHORE_FL , BOOK , BU_RISK_SYSTEM