SELECT
    a.COB_DATE,
    a.PRODUCT_TYPE_CODE,
    SUM (A.USD_IR_UNIFIED_PV01) AS USD_IR_UNIFIED_PV01
FROM cdwuser.U_DM_CC A
WHERE
    a.COB_DATE IN ('2018-02-28', '2018-01-31') AND 
    a.CCC_BUSINESS_AREA = 'MUNICIPAL SECURITIES' AND
    a.PRODUCT_TYPE_CODE IN ('BONDFUT', 'RATEFUT', 'GVTBOND', 'MUNI', 'MUNI_TAXABLE', 'SWAPTION', 'SWAP', 'BOND', 'BONDFUTOPT') AND
    A.MUNI_TYPE_CODE = 'HEDGES'
GROUP BY
    a.COB_DATE,
    a.PRODUCT_TYPE_CODE