Select
COB_DATE, 
a.PRODUCT_HIERARCHY_LEVEL7, 
a.CAPITAL_CHARGE_NETTING_KEY,
ABS(sum(coalesce(a.USD_NOTIONAL,0))) AS Notional 
from cdwuser.U_EXP_MSR a 
WHERE
    A.COB_DATE in ('2018-02-28','2018-01-31')
    and CCC_BUSINESS_AREA in ('DSP - CREDIT') 
Group by 
COB_DATE, 
a.PRODUCT_HIERARCHY_LEVEL7, 
a.CAPITAL_CHARGE_NETTING_KEY