with
 PRODUCT_LINE_VALUE(ccc_product_line) as ( values ('CRE LEND SECURITIZATION'),('CRE LEND - BANK HFI/HFS'),('CRE LENDING'),('CRE LENDING SEC/HFS'),('CREL BANK HFI'))

SELECT
b.COB_DATE,
b.CATEGORY,
b.vintage,
SUM(NET_EXPOSURE) USD_EXPOSURE
FROM
(

SELECT
a.COB_DATE,
a.vintage,
UNNEST(ARRAY[
CLASSIFICATION_0,
CLASSIFICATION_1,
CLASSIFICATION_2,
CLASSIFICATION_3,
CLASSIFICATION_4,
CLASSIFICATION_5,
CLASSIFICATION_6]) CATEGORY,
NET_EXPOSURE
FROM 
(

SELECT
COB_DATE, 
vintage,
Case when INSURER_RATING in ('AAA','AM','AS') then 'US CMBS AAA Index Concentration' end CLASSIFICATION_0, 
Case when INSURER_RATING in ('AA') then 'US CMBS AA Index Concentration' end CLASSIFICATION_1,
Case when INSURER_RATING in ('A') then 'US CMBS A Index Concentration' end CLASSIFICATION_2,
Case when INSURER_RATING in ('AJ') then 'US CMBS AJ Index Concentration' end CLASSIFICATION_3,
Case when INSURER_RATING in ('BBB') then 'US CMBS BBB Index Concentration' end CLASSIFICATION_4,
Case when INSURER_RATING in ('BBB-') then 'US CMBS BBB- Index Concentration' end CLASSIFICATION_5,
Case when INSURER_RATING in ('BB') then 'US CMBS BB Index Concentration' end CLASSIFICATION_6,
SUM(USD_EXPOSURE) AS NET_EXPOSURE
FROM CDWUSER.U_EXP_MSR

WHERE
COB_DATE IN ('2018-02-28', '2018-02-27')
AND CCC_BUSINESS_AREA in ('SECURITIZED PRODUCTS GRP') 
AND CCC_PRODUCT_LINE NOT in (select ccc_product_line from PRODUCT_LINE_VALUE)
AND CCC_PL_REPORTING_REGION = 'AMERICAS' AND SPG_PRODUCT_TYPE_GROUP in ('CMBS') AND PRODUCT_SUB_TYPE_CODE = 'CMBX'

group by 
COB_DATE, 
vintage,
CLASSIFICATION_0,
CLASSIFICATION_1,
CLASSIFICATION_2,
CLASSIFICATION_3,
CLASSIFICATION_4,
CLASSIFICATION_5,
CLASSIFICATION_6
) A
) B  
WHERE
b.CATEGORY IS NOT NULL
GROUP BY
b.COB_DATE, 
b.CATEGORY,
b.vintage