SELECT
    a.RATING_B, 
    A.TERM_OF_POSITION_BUCKETED,
    a.COB_DATE,
    SUM (A.USD_PV01SPRD) AS USD_PV01SPRD
FROM cdwuser.U_DM_CC A
WHERE
    A.COB_DATE IN ('2018-02-28') AND 
    A.MUNI_TYPE_CODE IS NOT NULL AND
    a.CCC_BUSINESS_AREA = 'MUNICIPAL SECURITIES' AND
    a.PRODUCT_TYPE_CODE IN ('MUNI', 'MUNI_TAXABLE')
GROUP BY
    a.COB_DATE,
    A.TERM_OF_POSITION_BUCKETED,
    a.RATING_B