select sum(a.USD_PV10_BENCH)*1000 as PV10,
sum(a.USD_NET_EXPOSURE) as NET_EXPOSURE, a.COB_DATE,
a.ISSUER_COUNTRY_CODE, 
POSITION_ULT_ISSUER_PARTY_DARWIN_NAME,
case when a.ISSUER_COUNTRY_CODE in ('CHN','HKG','IND','IDN','KOR','MYS','PHL','SGP','TWN','THA','VNM','PAK','LKA','MNG','BGD','MAC') then 'Asia' when a.ISSUER_COUNTRY_CODE in ('RUS','KAZ','UKR','AZE','BLR','GEO', 'BGR', 'HRV', 'BIH', 'CZE', 'EST', 'HUN', 'ISL', 'LVA', 'POL', 'ROM', 'SRB', 'SVK', 'SVN', 'TUR', 'BHR', 'CIV', 'EGY', 'ISR', 'KWT', 'LBR', 'MAR', 'NGA', 'QAT', 'SAU', 'ZAF', 'ARE', 'GHA', 'COG', 'IRQ', 'LBN', 'LTU', 'ROU', 'TUN', 'KEN', 'ZMB', 'GAB', 'SEN', 'JOR', 'TZA', 'RWA', 'NAM', 'ARM', 'ETH', 'AGO', 'MNE', 'CMR', 'MOZ','BDI', 'MUS', 'TJK', 'OMN', 'MDA') then 'EMEA' when a.ISSUER_COUNTRY_CODE in ('ARG','BRA','CHL','COL','CRI','JAM','MEX','PER','VEN','DOM','ECU','GTM','PAN','URY','SLV','BRB','GUY','HND','PRY','TTO','BHS', 'PRI') then 'LatAm' else 'Other' end as Country_Grouping,
CASE when a.currency_of_measure in ('AUD','CAD','CHF','DKK','EUR','GBP','JPY','NOK','NZD','SEK','USD','UBD') THEN 'MAJOR' else 'Other' end as currency_group,
case when ISSUER_COUNTRY_CODE not in ('DNK','BMU','CYM','AUS','AUT','BEL','CAN','CHE','DEU','ESP','FIN','FRA','GBR','GRC','IRL','ITA','JPN','LUX','NLD','NOR','NZL','PRT','SWE','USA','JEY','GGY','SUP','XS','XCI','VGB','CYP') then 'old exclusion' else 'no old exclusion' end as country_exclusion,
Case when ccc_product_line = 'ASIA CREDIT TRADING' then 'ASIA CREDIT' WHEN CCC_BUSINESS_AREA IN ('FXEM MACRO TRADING','EM CREDIT TRADING') THEN 'FXEM' else 'Other' end as Desk_Group
from cdwuser.U_dm_cc a where a.COB_DATE in ('2018-02-27') and a.ccc_division = ('FIXED INCOME DIVISION') and ((a.USD_NET_EXPOSURE <> 0 and a.USD_NET_EXPOSURE is not null) OR (a.USD_PV10_BENCH <> 0 and a.USD_PV10_BENCH is not null)) AND a.CCC_TAPS_COMPANY ='0302' AND a.CCC_BUSINESS_AREA NOT IN ('NON CORE','CPM','LENDING') AND a.CCC_BANKING_TRADING = 'TRADING' AND (a.CCC_PRODUCT_LINE NOT IN ('DISTRESSED TRADING') OR a.PRODUCT_TYPE_CODE IN ('CDSOPTIDX','CRDINDEX','LOANINDEX')) AND ((a.FID1_SENIORITY NOT IN ('AT1','SUBT1','SUBUT2') OR a.ISSUER_COUNTRY_CODE NOT IN ('DNK','BMU','CYM','AUS','AUT','BEL','CAN','CHE','DEU','ESP','FIN','FRA','GBR','GRC','IRL','ITA','JPN','LUX','NLD','NOR','NZL','PRT','SWE','USA','JEY','GGY','SUP','XS','XCI','VGB','CYP')) OR a.PRODUCT_TYPE_CODE NOT IN ('BOND','BONDFUT','BONDFUTOPT','BONDIL','BONDOPT','FRN','PREF')) AND a.VERTICAL_SYSTEM NOT LIKE '%SPG%' AND book not in ('OBTRS')
AND (a.FID1_INDUSTRY_NAME_LEVEL1 NOT IN ('SOVEREIGN', 'GOVERNMENT SPONSORED') 
OR a.ISSUER_COUNTRY_CODE NOT IN ('DNK','BMU','CYM','AUS','AUT','BEL','CAN','CHE','DEU','ESP','FIN','FRA','GBR','GRC','IRL','ITA','JPN','LUX','NLD','NOR','NZL','PRT','SWE','USA','JEY','GGY','SUP','XS','XCI','VGB','CYP')) group by a.COB_DATE,
a.ISSUER_COUNTRY_CODE, 
POSITION_ULT_ISSUER_PARTY_DARWIN_NAME,
case when a.ISSUER_COUNTRY_CODE in ('CHN','HKG','IND','IDN','KOR','MYS','PHL','SGP','TWN','THA','VNM','PAK','LKA','MNG','BGD','MAC') then 'Asia' when a.ISSUER_COUNTRY_CODE in ('RUS','KAZ','UKR','AZE','BLR','GEO', 'BGR', 'HRV', 'BIH', 'CZE', 'EST', 'HUN', 'ISL', 'LVA', 'POL', 'ROM', 'SRB', 'SVK', 'SVN', 'TUR', 'BHR', 'CIV', 'EGY', 'ISR', 'KWT', 'LBR', 'MAR', 'NGA', 'QAT', 'SAU', 'ZAF', 'ARE', 'GHA', 'COG', 'IRQ', 'LBN', 'LTU', 'ROU', 'TUN', 'KEN', 'ZMB', 'GAB', 'SEN', 'JOR', 'TZA', 'RWA', 'NAM', 'ARM', 'ETH', 'AGO', 'MNE', 'CMR', 'MOZ','BDI', 'MUS', 'TJK', 'OMN', 'MDA') then 'EMEA' when a.ISSUER_COUNTRY_CODE in ('ARG','BRA','CHL','COL','CRI','JAM','MEX','PER','VEN','DOM','ECU','GTM','PAN','URY','SLV','BRB','GUY','HND','PRY','TTO','BHS', 'PRI') then 'LatAm' else 'Other' end,
CASE when a.currency_of_measure in ('AUD','CAD','CHF','DKK','EUR','GBP','JPY','NOK','NZD','SEK','USD','UBD') THEN 'MAJOR' else 'Other' end,
case when ISSUER_COUNTRY_CODE not in ('DNK','BMU','CYM','AUS','AUT','BEL','CAN','CHE','DEU','ESP','FIN','FRA','GBR','GRC','IRL','ITA','JPN','LUX','NLD','NOR','NZL','PRT','SWE','USA','JEY','GGY','SUP','XS','XCI','VGB','CYP') then 'old exclusion' else 'no old exclusion' end,
Case when ccc_product_line = 'ASIA CREDIT TRADING' then 'ASIA CREDIT' WHEN CCC_BUSINESS_AREA IN ('FXEM MACRO TRADING','EM CREDIT TRADING') THEN 'FXEM' else 'Other' end