SELECT
    TAPSCUSIP,
    POSITION_ULT_ISSUER_PARTY_DARWIN_NAME,
    CASE 
    when SPG_DESC = 'RMBS SD LOAN' THEN 'NPL LOAN' 
    when SPG_DESC = 'RMBS PRIME LOAN' THEN 'PRIME LOAN'
    when SPG_DESC like '%PRIME DEFAULT SWAP%' then 'Prime CDS'
    when SPG_DESC like '%DEFAULT SWAP%' then 'ExPrime CDS'
    when SPG_DESC like '%SUB PRIME INDEX%' then 'ExPrime Index'
    when SPG_DESC like '%PRIME INDEX%' then 'Prime Index'
    when SPG_DESC like '%CDO%' then 'CDO'
    when SPG_DESC like '%REREMIC%' then 'Reremics'
    when SPG_DESC like '%ALTA IO%' then 'ALTA IO'    
    when SPG_DESC like '%ALTA%' then 'ALTA'    
    when SPG_DESC like '%OPTION ARM IO%' then 'OptionARM IO' 
    when SPG_DESC like '%OPTION ARM%' then 'OptionARM'
    when SPG_DESC like '%SUB PRIME IO%' then 'Subprime IO'
    when SPG_DESC like '%SUB PRIME%' then 'Subprime'
    when SPG_DESC like '%PRIME IO%' then 'Prime IO'    
    when SPG_DESC like '%PRIME%' then 'Prime' 
    when SPG_DESC in ('RMBS PRIME RESIDUAL', 'RMBS NIMS', 'RMBS SECOND SECURITY') then 'Residual' END AS GROUPED_RMBS,
    CASE WHEN a.POSITION_ISSUER_PARTY_DARWIN_NAME in ('TESCO PLC','TESCO PROPERTY FINANCE 6 PLC','LAKESIDE ASSET MANAGEMENT', 'AEOLOS S.A', 'MORTGAGE FUNDING 2008-1 PLC','FASTNET SECURITIES 9 LIMITED', 'BERICA PMI S.R.L.','MARCHE MUTUI SRL','MARCHE MUTUI 4 S.R.L.','DELAMARE FINANCE PLC','DRAGON FINANCE B.V.') THEN 'HIGHER' 
    WHEN SPG_DESC = 'CMBS MEZZANINE LOAN' THEN 'CMBS LOAN'
    WHEN SPG_DESC = 'RMBS SD LOAN' THEN 'NPL LOAN' 
    WHEN SPG_DESC = 'RMBS PRIME LOAN' THEN 'PRIME LOAN'
    WHEN SPG_PRODUCT_TYPE_GROUP IN ('CORPORATE', 'RESI- NON AGENCY', 'SUBPRIME') AND SPG_PRODUCT_TYPE NOT IN ('CORPORATE SINGLE NAME','CORPORATE SINGLE NAME INDEX','RESI- NON AGENCY ALT A REREMIC','RESI- NON AGENCY PRIME LOAN','RESI- NON AGENCY PRIME REREMIC','RESI- NON AGENCY SCRATCH & DENT','SUBPRIME CDO','SUBPRIME REREMIC') AND INSURER_RATING NOT IN ('AAA','PENAAA','AM','AS') THEN 'LOWER' 
    WHEN INSURER_RATING IN ('AAA','PENAAA','AM', 'AS') AND SPG_DESC like 'CMBS%' THEN 'HIGHER' 
    WHEN INSURER_RATING NOT IN ('AAA','PENAAA','AM', 'AS') AND SPG_DESC like 'CMBS%' THEN 'LOWER' 
    WHEN INSURER_RATING NOT IN ('AAA','PENAAA','AM', 'AS') AND SPG_PRODUCT_TYPE_GROUP = 'ABS' AND DETACHMENT < 1 THEN 'LOWER' 
    WHEN SPG_PRODUCT_TYPE IN ('CMBS CDO', 'SUBPRIME CDO') THEN 'LOWER' 
    WHEN SPG_PRODUCT_TYPE_GROUP = 'CMBS' AND SPG_PRODUCT_TYPE = 'CMBS LOAN' AND BOOK = 'CMBS_SECONDARY' THEN 'LOWER' 
    WHEN SPG_DESC IN ('RMBS CDO') THEN 'LOWER' else 'HIGHER' END AS GROUPED_RATING,    
    SUM (CASE WHEN COB_DATE = '2018-02-28' then USD_EXPOSURE else 0 end) AS NET_EXPOSURE,
    ABS(SUM (CASE WHEN COB_DATE = '2018-02-28' then USD_EXPOSURE else 0 end)) AS ABS_NET_EXPOSURE,
    SUM (CASE WHEN COB_DATE = '2018-02-28' then USD_EXPOSURE else -USD_EXPOSURE end) AS NET_EXPOSURE_DOD
FROM cdwuser.U_CR_MSR a
WHERE
    a.COB_DATE IN 
    ('2018-02-28', '2018-02-27')
    AND a.CCC_BUSINESS_AREA = 'SECURITIZED PRODUCTS GRP'    
    AND CCC_PL_REPORTING_REGION = 'AMERICAS'
    AND spg_desc like '%RMBS%' and spg_desc not like '%AGENCY%' and CCC_PRODUCT_LINE not in ('WAREHOUSE', 'AGENCY MORTGAGE TRADING')
    AND (SPG_DESC like '%PRIME%' or SPG_DESC like '%CDO%' OR SPG_DESC like '%REREMIC%' OR SPG_DESC like '%ALTA%' OR SPG_DESC like '%OPTION ARM%' OR SPG_DESC in ('RMBS PRIME RESIDUAL', 'RMBS NIMS', 'RMBS SECOND SECURITY'))
    AND NOT (SPG_DESC like '%LOAN%' OR SPG_DESC like '%DEFAULT SWAP%' OR SPG_DESC like '%INDEX%')
GROUP BY
    TAPSCUSIP,
    POSITION_ULT_ISSUER_PARTY_DARWIN_NAME,
    CASE 
    when SPG_DESC = 'RMBS SD LOAN' THEN 'NPL LOAN' 
    when SPG_DESC = 'RMBS PRIME LOAN' THEN 'PRIME LOAN'
    when SPG_DESC like '%PRIME DEFAULT SWAP%' then 'Prime CDS'
    when SPG_DESC like '%DEFAULT SWAP%' then 'ExPrime CDS'
    when SPG_DESC like '%SUB PRIME INDEX%' then 'ExPrime Index'
    when SPG_DESC like '%PRIME INDEX%' then 'Prime Index'
    when SPG_DESC like '%CDO%' then 'CDO'
    when SPG_DESC like '%REREMIC%' then 'Reremics'
    when SPG_DESC like '%ALTA IO%' then 'ALTA IO'    
    when SPG_DESC like '%ALTA%' then 'ALTA'    
    when SPG_DESC like '%OPTION ARM IO%' then 'OptionARM IO' 
    when SPG_DESC like '%OPTION ARM%' then 'OptionARM'
    when SPG_DESC like '%SUB PRIME IO%' then 'Subprime IO'
    when SPG_DESC like '%SUB PRIME%' then 'Subprime'
    when SPG_DESC like '%PRIME IO%' then 'Prime IO'    
    when SPG_DESC like '%PRIME%' then 'Prime' 
    when SPG_DESC in ('RMBS PRIME RESIDUAL', 'RMBS NIMS', 'RMBS SECOND SECURITY') then 'Residual' END,
    CASE WHEN a.POSITION_ISSUER_PARTY_DARWIN_NAME in ('TESCO PLC','TESCO PROPERTY FINANCE 6 PLC','LAKESIDE ASSET MANAGEMENT', 'AEOLOS S.A', 'MORTGAGE FUNDING 2008-1 PLC','FASTNET SECURITIES 9 LIMITED', 'BERICA PMI S.R.L.','MARCHE MUTUI SRL','MARCHE MUTUI 4 S.R.L.','DELAMARE FINANCE PLC','DRAGON FINANCE B.V.') THEN 'HIGHER' 
    WHEN SPG_DESC = 'CMBS MEZZANINE LOAN' THEN 'CMBS LOAN'
    WHEN SPG_DESC = 'RMBS SD LOAN' THEN 'NPL LOAN' 
    WHEN SPG_DESC = 'RMBS PRIME LOAN' THEN 'PRIME LOAN'
    WHEN SPG_PRODUCT_TYPE_GROUP IN ('CORPORATE', 'RESI- NON AGENCY', 'SUBPRIME') AND SPG_PRODUCT_TYPE NOT IN ('CORPORATE SINGLE NAME','CORPORATE SINGLE NAME INDEX','RESI- NON AGENCY ALT A REREMIC','RESI- NON AGENCY PRIME LOAN','RESI- NON AGENCY PRIME REREMIC','RESI- NON AGENCY SCRATCH & DENT','SUBPRIME CDO','SUBPRIME REREMIC') AND INSURER_RATING NOT IN ('AAA','PENAAA','AM','AS') THEN 'LOWER' 
    WHEN INSURER_RATING IN ('AAA','PENAAA','AM', 'AS') AND SPG_DESC like 'CMBS%' THEN 'HIGHER' 
    WHEN INSURER_RATING NOT IN ('AAA','PENAAA','AM', 'AS') AND SPG_DESC like 'CMBS%' THEN 'LOWER' 
    WHEN INSURER_RATING NOT IN ('AAA','PENAAA','AM', 'AS') AND SPG_PRODUCT_TYPE_GROUP = 'ABS' AND DETACHMENT < 1 THEN 'LOWER' 
    WHEN SPG_PRODUCT_TYPE IN ('CMBS CDO', 'SUBPRIME CDO') THEN 'LOWER' 
    WHEN SPG_PRODUCT_TYPE_GROUP = 'CMBS' AND SPG_PRODUCT_TYPE = 'CMBS LOAN' AND BOOK = 'CMBS_SECONDARY' THEN 'LOWER' 
    WHEN SPG_DESC IN ('RMBS CDO') THEN 'LOWER' else 'HIGHER' END