SELECT
    a.COB_DATE,
    a.CCC_PL_REPORTING_REGION,
CASE WHEN SPG_DESC in ('RMBS ALTA DEFAULT SWAP', 'RMBS CDO DEFAULT SWAP', 'RMBS DEFAULT SWAP', 'RMBS PRIME DEFAULT SWAP','RMBS PRIME DEFAULT SWAP', 'RMBS NON CONFORMING DEFAULT SWAP', 'CMBS DEFAULT SWAP') THEN 'CDS' 
WHEN SPG_DESC IN ('RMBS INDEX TRANCHE', 'RMBS SUB PRIME INDEX', 'RMBS PRIME INDEX', 'CMBS INDEX') THEN 'Index'
ELSE 'CASH' END AS CASH_SYNTHETIC,
CASE WHEN VINTAGE in ('04-1','04-2','04-3','04-4','05-1','05-2','05-3','05-4','06-1','06-2','06-3','06-4','07-1','07-2','07-3','07-4','08-1','08-2','08-3','08-4','09-1','09-2','09-3','09-4','PRE04','N/A') then '1.0'
else '2.0' end as GROUPED_VINTAGE,
CASE 
 when SPG_PRODUCT_TYPE IN ('RESI- NON AGENCY CRT') then 'RMBS'
 when spg_desc in ('WAREHOUSE CLO') then 'Warehouse - FV'
 when spg_desc like 'WAREHOUSE%' then 'Warehouse - HFI' 
 when SPG_DESC ='OTHER RMBS' or SPG_DESC like '%AGENCY%' or spg_desc like '%POOL%' or spg_desc like '%TBA%' or spg_desc like '%RMBS IOS%' or spg_desc like '%RMBS MBX%' or spg_desc like '%RMBS MBS%' then 'Agency' 
 when spg_desc like '%CMBS%' and spg_desc not in ('CMBS LOAN', 'CMBS LOAN IO') then 'CMBS' 
 when spg_desc like '%RMBS%' and spg_desc not like '%AGENCY%' and CCC_PRODUCT_LINE not in ('WAREHOUSE', 'AGENCY MORTGAGE TRADING') then 'RMBS' 
 when ccc_product_line in ('CRE LEND SECURITIZATION', 'CRE LEND - BANK HFI/HFS', 'CRE LENDING','CRE LENDING SEC/HFS','CREL BANK HFI') and book like '%HFI' and spg_desc in ('CMBS LOAN', 'CMBS LOAN IO') then 'CRE Loan - HFI' 
 when ccc_product_line in ('CRE LEND SECURITIZATION', 'CRE LEND - BANK HFI/HFS', 'CRE LENDING','CRE LENDING SEC/HFS','CREL BANK HFI') and book in ('CRE_LENDING_EU', 'CRE_LENDING') and spg_desc in ('CMBS LOAN', 'CMBS LOAN IO') then 'CRE Loan - FV' 
 when ccc_product_line in ('CRE LEND SECURITIZATION', 'CRE LEND - BANK HFI/HFS', 'CRE LENDING','CRE LENDING SEC/HFS','CREL BANK HFI') and book in ('CRE_LENDING_EU_HFS', 'CRE_LENDING_HFS') and spg_desc in ('CMBS LOAN', 'CMBS LOAN IO') then 'CRE Loan - HFS' 
 when spg_desc in ('ABS STUDENT SECURITY') then 'ABS Agency' 
 when spg_desc like 'ABS%' then 'ABS' 
 when spg_desc like '%CORPORATE CDO%' or spg_desc like '%CORPORATE CLO%' then 'CLO' 
 when spg_desc like '%CORPORATE INDEX%' or spg_desc like '%CORPORATE DEFAULT SWAP%' then 'Corporate Hedge' 
 when spg_desc like '%GOVERNMENT%' or spg_desc like '%RATE%' or spg_desc in ('SWAP','SWAPS') or PRODUCT_TYPE_CODE in ('BERMUDAN_SWAPTION_VA','BONDFUTOPT','MISC') then 'Rate Hedge' 
 WHEN SPG_DESC = 'OTHER' AND PRODUCT_TYPE_CODE = 'AGN' THEN 'Agency Debentures'
Else 'OTHER'  end as GROUPED_TRADING_LENDING,
CASE WHEN a.POSITION_ISSUER_PARTY_DARWIN_NAME in ('TESCO PLC','TESCO PROPERTY FINANCE 6 PLC','LAKESIDE ASSET MANAGEMENT', 'AEOLOS S.A', 'MORTGAGE FUNDING 2008-1 PLC','FASTNET SECURITIES 9 LIMITED', 'BERICA PMI S.R.L.','MARCHE MUTUI SRL','MARCHE MUTUI 4 S.R.L.','DELAMARE FINANCE PLC','DRAGON FINANCE B.V.') THEN 'HIGHER' 
 WHEN SPG_DESC = 'CMBS MEZZANINE LOAN' THEN 'CMBS LOAN'
 WHEN SPG_DESC = 'RMBS SD LOAN' THEN 'NPL LOAN' 
 WHEN SPG_DESC = 'RMBS PRIME LOAN' THEN 'PRIME LOAN'
 WHEN SPG_PRODUCT_TYPE_GROUP IN ('CORPORATE', 'RESI- NON AGENCY', 'SUBPRIME') AND SPG_PRODUCT_TYPE NOT IN ('CORPORATE SINGLE NAME','CORPORATE SINGLE NAME INDEX','RESI- NON AGENCY ALT A REREMIC','RESI- NON AGENCY PRIME LOAN','RESI- NON AGENCY PRIME REREMIC','RESI- NON AGENCY SCRATCH & DENT','SUBPRIME CDO','SUBPRIME REREMIC') AND INSURER_RATING NOT IN ('AAA','PENAAA','AM','AS') THEN 'LOWER' 
 WHEN INSURER_RATING IN ('AAA','PENAAA','AM', 'AS') AND SPG_DESC like 'CMBS%' THEN 'HIGHER' 
 WHEN INSURER_RATING NOT IN ('AAA','PENAAA','AM', 'AS') AND SPG_DESC like 'CMBS%' THEN 'LOWER' 
 WHEN INSURER_RATING NOT IN ('AAA','PENAAA','AM', 'AS') AND SPG_PRODUCT_TYPE_GROUP = 'ABS' AND DETACHMENT < 1 THEN 'LOWER' 
 WHEN SPG_PRODUCT_TYPE IN ('CMBS CDO', 'SUBPRIME CDO') THEN 'LOWER' 
 WHEN SPG_PRODUCT_TYPE_GROUP = 'CMBS' AND SPG_PRODUCT_TYPE = 'CMBS LOAN' AND BOOK = 'CMBS_SECONDARY' THEN 'LOWER' 
 WHEN SPG_DESC IN ('RMBS CDO') THEN 'LOWER' else 'HIGHER' 
 END AS GROUPED_RATING,
    SUM (a.USD_EXPOSURE) AS NET_EXPOSURE
FROM cdwuser.U_CR_MSR a
WHERE
    a.COB_DATE IN 
    ('2018-02-28', '2018-01-31', '2017-12-29', '2017-09-29', '2017-06-30')
    AND a.CCC_BUSINESS_AREA = 'SECURITIZED PRODUCTS GRP'
    AND NOT a.CCC_PRODUCT_LINE IN ('CRE LENDING SEC/HFS', 'CREL BANK HFI', 'CRE LENDING', 'WAREHOUSE')
    AND NOT (a.SPG_DESC = 'CMBS INDEX' AND
         a.CCC_PRODUCT_LINE IN ('CRE LENDING SEC/HFS', 'CREL BANK HFI', 'CRE LENDING', 'SPG MANAGEMENT'))
GROUP BY
    a.COB_DATE,
    a.CCC_PL_REPORTING_REGION,
CASE WHEN SPG_DESC in ('RMBS ALTA DEFAULT SWAP', 'RMBS CDO DEFAULT SWAP', 'RMBS DEFAULT SWAP', 'RMBS PRIME DEFAULT SWAP','RMBS PRIME DEFAULT SWAP', 'RMBS NON CONFORMING DEFAULT SWAP', 'CMBS DEFAULT SWAP') THEN 'CDS' 
WHEN SPG_DESC IN ('RMBS INDEX TRANCHE', 'RMBS SUB PRIME INDEX', 'RMBS PRIME INDEX', 'CMBS INDEX') THEN 'Index'
ELSE 'CASH' END,
CASE WHEN VINTAGE in ('04-1','04-2','04-3','04-4','05-1','05-2','05-3','05-4','06-1','06-2','06-3','06-4','07-1','07-2','07-3','07-4','08-1','08-2','08-3','08-4','09-1','09-2','09-3','09-4','PRE04','N/A') then '1.0'
else '2.0' end,
CASE 
 when SPG_PRODUCT_TYPE IN ('RESI- NON AGENCY CRT') then 'RMBS'
 when spg_desc in ('WAREHOUSE CLO') then 'Warehouse - FV'
 when spg_desc like 'WAREHOUSE%' then 'Warehouse - HFI' 
 when SPG_DESC ='OTHER RMBS' or SPG_DESC like '%AGENCY%' or spg_desc like '%POOL%' or spg_desc like '%TBA%' or spg_desc like '%RMBS IOS%' or spg_desc like '%RMBS MBX%' or spg_desc like '%RMBS MBS%' then 'Agency' 
 when spg_desc like '%CMBS%' and spg_desc not in ('CMBS LOAN', 'CMBS LOAN IO') then 'CMBS' 
 when spg_desc like '%RMBS%' and spg_desc not like '%AGENCY%' and CCC_PRODUCT_LINE not in ('WAREHOUSE', 'AGENCY MORTGAGE TRADING') then 'RMBS' 
 when ccc_product_line in ('CRE LEND SECURITIZATION', 'CRE LEND - BANK HFI/HFS', 'CRE LENDING','CRE LENDING SEC/HFS','CREL BANK HFI') and book like '%HFI' and spg_desc in ('CMBS LOAN', 'CMBS LOAN IO') then 'CRE Loan - HFI' 
 when ccc_product_line in ('CRE LEND SECURITIZATION', 'CRE LEND - BANK HFI/HFS', 'CRE LENDING','CRE LENDING SEC/HFS','CREL BANK HFI') and book in ('CRE_LENDING_EU', 'CRE_LENDING') and spg_desc in ('CMBS LOAN', 'CMBS LOAN IO') then 'CRE Loan - FV' 
 when ccc_product_line in ('CRE LEND SECURITIZATION', 'CRE LEND - BANK HFI/HFS', 'CRE LENDING','CRE LENDING SEC/HFS','CREL BANK HFI') and book in ('CRE_LENDING_EU_HFS', 'CRE_LENDING_HFS') and spg_desc in ('CMBS LOAN', 'CMBS LOAN IO') then 'CRE Loan - HFS' 
 when spg_desc in ('ABS STUDENT SECURITY') then 'ABS Agency' 
 when spg_desc like 'ABS%' then 'ABS' 
 when spg_desc like '%CORPORATE CDO%' or spg_desc like '%CORPORATE CLO%' then 'CLO' 
 when spg_desc like '%CORPORATE INDEX%' or spg_desc like '%CORPORATE DEFAULT SWAP%' then 'Corporate Hedge' 
 when spg_desc like '%GOVERNMENT%' or spg_desc like '%RATE%' or spg_desc in ('SWAP','SWAPS') or PRODUCT_TYPE_CODE in ('BERMUDAN_SWAPTION_VA','BONDFUTOPT','MISC') then 'Rate Hedge' 
 WHEN SPG_DESC = 'OTHER' AND PRODUCT_TYPE_CODE = 'AGN' THEN 'Agency Debentures'
Else 'OTHER'  end,
CASE WHEN a.POSITION_ISSUER_PARTY_DARWIN_NAME in ('TESCO PLC','TESCO PROPERTY FINANCE 6 PLC','LAKESIDE ASSET MANAGEMENT', 'AEOLOS S.A', 'MORTGAGE FUNDING 2008-1 PLC','FASTNET SECURITIES 9 LIMITED', 'BERICA PMI S.R.L.','MARCHE MUTUI SRL','MARCHE MUTUI 4 S.R.L.','DELAMARE FINANCE PLC','DRAGON FINANCE B.V.') THEN 'HIGHER' 
 WHEN SPG_DESC = 'CMBS MEZZANINE LOAN' THEN 'CMBS LOAN'
 WHEN SPG_DESC = 'RMBS SD LOAN' THEN 'NPL LOAN' 
 WHEN SPG_DESC = 'RMBS PRIME LOAN' THEN 'PRIME LOAN'
 WHEN SPG_PRODUCT_TYPE_GROUP IN ('CORPORATE', 'RESI- NON AGENCY', 'SUBPRIME') AND SPG_PRODUCT_TYPE NOT IN ('CORPORATE SINGLE NAME','CORPORATE SINGLE NAME INDEX','RESI- NON AGENCY ALT A REREMIC','RESI- NON AGENCY PRIME LOAN','RESI- NON AGENCY PRIME REREMIC','RESI- NON AGENCY SCRATCH & DENT','SUBPRIME CDO','SUBPRIME REREMIC') AND INSURER_RATING NOT IN ('AAA','PENAAA','AM','AS') THEN 'LOWER' 
 WHEN INSURER_RATING IN ('AAA','PENAAA','AM', 'AS') AND SPG_DESC like 'CMBS%' THEN 'HIGHER' 
 WHEN INSURER_RATING NOT IN ('AAA','PENAAA','AM', 'AS') AND SPG_DESC like 'CMBS%' THEN 'LOWER' 
 WHEN INSURER_RATING NOT IN ('AAA','PENAAA','AM', 'AS') AND SPG_PRODUCT_TYPE_GROUP = 'ABS' AND DETACHMENT < 1 THEN 'LOWER' 
 WHEN SPG_PRODUCT_TYPE IN ('CMBS CDO', 'SUBPRIME CDO') THEN 'LOWER' 
 WHEN SPG_PRODUCT_TYPE_GROUP = 'CMBS' AND SPG_PRODUCT_TYPE = 'CMBS LOAN' AND BOOK = 'CMBS_SECONDARY' THEN 'LOWER' 
 WHEN SPG_DESC IN ('RMBS CDO') THEN 'LOWER' else 'HIGHER' END