SELECT 'FID MBS KAPPA 10PC' AS CATEGORY, 
COB_DATE, 
SPG_PRODUCT_TYPE_GROUP,  
SPG_PRODUCT_TYPE, 
SUM(I.USD_IR_KAPPA)/10 AS IR_KAPPA 
FROM cdwuser.U_IR_MSR I 
WHERE
COB_DATE IN ('2018-02-28', '2018-02-27')
and CCC_DIVISION='FIXED INCOME DIVISION' 
AND (I.VERTICAL_SYSTEM LIKE 'SPG%' or I.VERTICAL_SYSTEM LIKE 'MBS%') 
AND USD_IR_KAPPA IS NOT NULL 
AND CCC_PRODUCT_LINE NOT IN ('CRE LENDING', 'CRE LENDING SEC/HFS', 'CREL BANK HFI') 
GROUP BY SPG_PRODUCT_TYPE_GROUP 
,SPG_PRODUCT_TYPE 
,COB_DATE