SELECT
    COB_DATE,
    CCC_PRODUCT_LINE,
    case WHEN BOOK = 'ABCHN' Then 'DSP Index Products'
    WHEN CCC_STRATEGY in ('LEGACY MUNI DERIVATIVES','LEGACY BESPOKE CDOS', 'LEGACY FLOW CDS', 'LEGACY HF DERIVS EU',  'LEGACY PORTFOLIO TRADING CDP', 'LEGACY TRANCHED INDEX EU', 'MANAGEMENT OTHER CDP') or CCC_PRODUCT_LINE = 'DSP LEGACY' Then 'DSP Legacy'
    WHEN (CCC_PRODUCT_LINE = 'DSP TRS FINANCING' or CCC_STRATEGY = 'DSP TRS FINANCING1') Then 'DSP TRS Financing'
    WHEN CCC_PRODUCT_LINE = 'DSP EXOTICS' or CCC_STRATEGY in ('EXOTICS CDP', 'FULL CAP BESPOKE') Then 'DSP Exotics'
    else 'DSP Index Products' end as PRODUCT_LINE, 
    CASE WHEN PRODUCT_TYPE_CODE in ('TRS BOND ETF', 'TRS LOAN ETF') THEN 'TRS INDEX'
    WHEN PRODUCT_HIERARCHY_LEVEL7 in ('CR_BONDETF', 'CR_LOANETF') THEN 'ETF'
    WHEN REFERENCE_INDEX_ENTITY_NAME LIKE '%CDX.NA.IG%' THEN 'CDX IG' 
    WHEN REFERENCE_INDEX_ENTITY_NAME LIKE '%CDX.NA.HY%' THEN 'CDX HY'
    WHEN REFERENCE_INDEX_ENTITY_NAME LIKE '%ITRAXX EUROPE CROSSOVER%' THEN 'iTraxx XO' 
    WHEN REFERENCE_INDEX_ENTITY_NAME LIKE '%ITRAXX EUROPE SENIOR%' THEN 'Other' 
    WHEN REFERENCE_INDEX_ENTITY_NAME LIKE '%ITRAXX EUROPE SUB%' THEN 'Other' 
    WHEN REFERENCE_INDEX_ENTITY_NAME LIKE '%ITRAXX EUROPE%' THEN 'iTraxx Main'
    ELSE 'Other' END AS Index_Class,
SUM(Case When ARB_ADJ_INDEX_SHORT_NAME = 'UNDEFINED' THEN Coalesce(USD_PV10_BENCH,0) ELSE Coalesce(USD_PV10_BENCH_COMP,0) END) as PV10_COMBINED            
FROM cdwuser.U_CR_MSR A
        WHERE
            a.COB_DATE IN (
'2018-02-28', 
'2018-01-31', 
'2017-12-29', 
'2017-11-30', 
'2017-10-31') AND
    (CCC_BUSINESS_AREA = 'DSP - CREDIT' or
    CCC_PRODUCT_LINE = 'INDEX PROD TRADING - NA' or 
     a.CCC_COST_CENTER_CODE = 'Q476') 

GROUP BY
    COB_DATE,
    CCC_PRODUCT_LINE,
    case WHEN BOOK = 'ABCHN' Then 'DSP Index Products'
    WHEN CCC_STRATEGY in ('LEGACY MUNI DERIVATIVES','LEGACY BESPOKE CDOS', 'LEGACY FLOW CDS', 'LEGACY HF DERIVS EU',  'LEGACY PORTFOLIO TRADING CDP', 'LEGACY TRANCHED INDEX EU', 'MANAGEMENT OTHER CDP') or CCC_PRODUCT_LINE = 'DSP LEGACY' Then 'DSP Legacy'
    WHEN (CCC_PRODUCT_LINE = 'DSP TRS FINANCING' or CCC_STRATEGY = 'DSP TRS FINANCING1') Then 'DSP TRS Financing'
    WHEN CCC_PRODUCT_LINE = 'DSP EXOTICS' or CCC_STRATEGY in ('EXOTICS CDP', 'FULL CAP BESPOKE') Then 'DSP Exotics'
    else 'DSP Index Products' end, 
    CASE WHEN PRODUCT_TYPE_CODE in ('TRS BOND ETF', 'TRS LOAN ETF') THEN 'TRS INDEX'
    WHEN PRODUCT_HIERARCHY_LEVEL7 in ('CR_BONDETF', 'CR_LOANETF') THEN 'ETF'
    WHEN REFERENCE_INDEX_ENTITY_NAME LIKE '%CDX.NA.IG%' THEN 'CDX IG' 
    WHEN REFERENCE_INDEX_ENTITY_NAME LIKE '%CDX.NA.HY%' THEN 'CDX HY'
    WHEN REFERENCE_INDEX_ENTITY_NAME LIKE '%ITRAXX EUROPE CROSSOVER%' THEN 'iTraxx XO' 
    WHEN REFERENCE_INDEX_ENTITY_NAME LIKE '%ITRAXX EUROPE SENIOR%' THEN 'Other' 
    WHEN REFERENCE_INDEX_ENTITY_NAME LIKE '%ITRAXX EUROPE SUB%' THEN 'Other' 
    WHEN REFERENCE_INDEX_ENTITY_NAME LIKE '%ITRAXX EUROPE%' THEN 'iTraxx Main'
    ELSE 'Other' END