SELECT
    A.COB_DATE,
    A.SECTYPE2,
    A.EM_COUNTRY_REGION,
    SUM (A.USD_PV10_BENCH) AS USD_PV10_BENCH
FROM cdwuser.U_DM_CC A
WHERE
    a.COB_DATE IN ('2018-02-28', '2018-02-27') AND 

    a.CCC_PL_REPORTING_REGION in ('EMEA','EUROPE') AND 
    A.CCC_STRATEGY = 'EM CREDIT' AND
    A.COUNTRY_CD_OF_RISK NOT IN ('ARG', 'VEN', 'UKR')
GROUP BY
    A.SECTYPE2,
    A.COB_DATE,
    A.EM_COUNTRY_REGION