Select
COB_DATE,
Case when a.PRODUCT_HIERARCHY_LEVEL7 in ('CR_BESPOKE BASKET DEFAULT SWAPS', 'CR_BESPOKE BASKET DEFAULT SWAPS', 'CR_BESPOKE SYNTHETIC CLO', 
'CR_BESPOKE SYNTHETIC CLO (CANCELLABLE NAMES)', 'CR_FIRST TO DEFAULT BASKET SWAP', 'CR_FIRST_TO_DEFAULT_BASKET_SWAP_FIXED_RECOVERY', 
'CR_FIXED RECOVERY BASKET DEFAULT SWAP', 'CR_FIXED RECOVERY BESPOKE SYNTHETIC CLO', 'CR_RISKY COLLATERAL FOR CDO', 
'CR_RISKY COLLATERAL FOR CDO_FIXED_RECOVERY', 'CR_WRAPPED SEPARATE ACCOUNT', 'CR_BESPOKE BASKET DEFAULT SWAPS WITH EQUITY TRIGGER', 
'CR_RISKY_COLLATERAL_FOR_LONG_SHORT_CDO', 'CR_MS ISSUANCE_LOSS', 'CR_CDO2', 'CR_LEVERAGED SUPER SENIOR') Then 'Bespokes'
when a.PRODUCT_HIERARCHY_LEVEL7 in ('CR_LOAN TRANCHED INDEX DEFAULT SWAP', 'CR_OFF THE RUN TRANCHED INDEX DEFAULT SWAP', 
'CR_TRANCHED INDEX DEFAULT SWAP') Then 'Index Tranches'
Else 'Other' END as Flag,
Case
when a.EXPIRATION_DATE <= '2018-02-19' Then '02/19/2018'
when a.EXPIRATION_DATE <= '2018-06-30' Then 'Jun-18'
when a.EXPIRATION_DATE <= '2018-12-31' Then 'Dec-18'
when a.EXPIRATION_DATE <= '2019-06-30' Then 'Jun-19'
when a.EXPIRATION_DATE <= '2019-12-31' Then 'Dec-19'
when a.EXPIRATION_DATE <= '2020-06-30' Then 'Jun-20'
when a.EXPIRATION_DATE <= '2020-12-31' Then 'Dec-20'
when a.EXPIRATION_DATE <= '2021-06-30' Then 'Jun-21'
Else 'Long Term' END as Expiration,
a.CAPITAL_CHARGE_NETTING_KEY,
ABS(sum(coalesce(a.USD_NOTIONAL,0))) Notional
from cdwuser.U_EXP_MSR a 
where 
    A.COB_DATE in ('2018-02-28')
    and CCC_BUSINESS_AREA in ('DSP - CREDIT') 
Group by
COB_DATE,
Case when a.PRODUCT_HIERARCHY_LEVEL7 in ('CR_BESPOKE BASKET DEFAULT SWAPS', 'CR_BESPOKE BASKET DEFAULT SWAPS', 'CR_BESPOKE SYNTHETIC CLO', 
'CR_BESPOKE SYNTHETIC CLO (CANCELLABLE NAMES)', 'CR_FIRST TO DEFAULT BASKET SWAP', 'CR_FIRST_TO_DEFAULT_BASKET_SWAP_FIXED_RECOVERY', 
'CR_FIXED RECOVERY BASKET DEFAULT SWAP', 'CR_FIXED RECOVERY BESPOKE SYNTHETIC CLO', 'CR_RISKY COLLATERAL FOR CDO', 
'CR_RISKY COLLATERAL FOR CDO_FIXED_RECOVERY', 'CR_WRAPPED SEPARATE ACCOUNT', 'CR_BESPOKE BASKET DEFAULT SWAPS WITH EQUITY TRIGGER', 
'CR_RISKY_COLLATERAL_FOR_LONG_SHORT_CDO', 'CR_MS ISSUANCE_LOSS', 'CR_CDO2', 'CR_LEVERAGED SUPER SENIOR') Then 'Bespokes'
when a.PRODUCT_HIERARCHY_LEVEL7 in ('CR_LOAN TRANCHED INDEX DEFAULT SWAP', 'CR_OFF THE RUN TRANCHED INDEX DEFAULT SWAP', 
'CR_TRANCHED INDEX DEFAULT SWAP') Then 'Index Tranches'
Else 'Other' END,
Case
when a.EXPIRATION_DATE <= '2018-02-19' Then '02/19/2018'
when a.EXPIRATION_DATE <= '2018-06-30' Then 'Jun-18'
when a.EXPIRATION_DATE <= '2018-12-31' Then 'Dec-18'
when a.EXPIRATION_DATE <= '2019-06-30' Then 'Jun-19'
when a.EXPIRATION_DATE <= '2019-12-31' Then 'Dec-19'
when a.EXPIRATION_DATE <= '2020-06-30' Then 'Jun-20'
when a.EXPIRATION_DATE <= '2020-12-31' Then 'Dec-20'
when a.EXPIRATION_DATE <= '2021-06-30' Then 'Jun-21'
Else 'Long Term' END,
a.CAPITAL_CHARGE_NETTING_KEY