SELECT
    A.COB_DATE,
    A.POSITION_ULT_ISSUER_PARTY_DARWIN_NAME, 
    SUM (a.USD_NET_EXPOSURE) AS netexp
FROM cdwuser.U_DM_CC A
WHERE
    a.COB_DATE IN ('2018-02-28', '2018-01-31') AND 
    A.CCC_BUSINESS_AREA = 'CREDIT-CORPORATES' AND
    A.FID1_SENIORITY IN ('SUBT1', 'SUBUT2', 'AT1') AND
    A.CREDIT_TRADING_FLAG NOT IN ('Distressed','Distressed Hedges') AND
    A.BOOK NOT IN ('JVPMK', 'JVMK2') AND
    A.PRODUCT_TYPE_CODE IN ('BOND', 'PREF')
GROUP BY
    A.COB_DATE,
    A.POSITION_ULT_ISSUER_PARTY_DARWIN_NAME