Select 
COB_DATE, 
CASE WHEN CCC_STRATEGY = 'INDEX PROD TRADING - NA1' then 'NA INDEX TRADING'
          WHEN CCC_STRATEGY = 'EUROPEAN CREDIT FLOW1' then 'EU INDEX TRADING'
          WHEN CCC_STRATEGY = 'US INDEX TRANCHE' then 'NA INDEX TRANCHE'
          WHEN CCC_STRATEGY = 'TRS TRADING NA' then 'NA TRS INDEX TRADING'
          WHEN CCC_STRATEGY = 'OPTIONS' then 'EU INDEX OPTIONS'
          else CCC_STRATEGY end as CCC_STRATEGY,
sum(a.USD_SENSITIVITY_SCALED) CORR_01 
from cdwuser.U_DM_CC a 
WHERE
    A.COB_DATE in ('2018-02-28','2018-01-31')
    AND CCC_BUSINESS_AREA = 'DSP - CREDIT'
Group by 
COB_DATE, 
CASE WHEN CCC_STRATEGY = 'INDEX PROD TRADING - NA1' then 'NA INDEX TRADING'
          WHEN CCC_STRATEGY = 'EUROPEAN CREDIT FLOW1' then 'EU INDEX TRADING'
          WHEN CCC_STRATEGY = 'US INDEX TRANCHE' then 'NA INDEX TRANCHE'
          WHEN CCC_STRATEGY = 'TRS TRADING NA' then 'NA TRS INDEX TRADING'
          WHEN CCC_STRATEGY = 'OPTIONS' then 'EU INDEX OPTIONS'
          else CCC_STRATEGY end