SELECT
    CASE WHEN a.CCC_PRODUCT_LINE IN ('HIGH YIELD - EU', 'INV GRADE TRADING - EU') THEN 'EUROPEAN CREDIT FLOW' 
    WHEN a.CCC_PRODUCT_LINE IN ('INDEX PROD TRADING - NA', 'DSP CREDIT TDG', 'DSP INDEX PRODUCTS TRADING') THEN 'DSP INDEX PRODUCTS' ELSE  a.CCC_PRODUCT_LINE END AS CCC_PRODUCT_LINE,
    A.COB_DATE,
    A.RATING2,
    A.POSITION_ULT_ISSUER_PARTY_DARWIN_NAME,
    ABS (SUM (A.USD_PV10_BENCH)) AS ABS_USD_PV10_BENCH,
    ABS (SUM (A.USD_PV01SPRD)) AS ABS_USD_PV01SPRD
FROM cdwuser.U_DM_CC A
WHERE
    A.CREDIT_TRADING_FLAG = 'Flow Trading' AND
    A.CCC_BUSINESS_AREA IN ('CREDIT-CORPORATES', 'DSP - CREDIT') AND
    A.COB_DATE in ('2018-02-28','2018-01-31')
GROUP BY
    CASE WHEN a.CCC_PRODUCT_LINE IN ('HIGH YIELD - EU', 'INV GRADE TRADING - EU') THEN 'EUROPEAN CREDIT FLOW' 
    WHEN a.CCC_PRODUCT_LINE IN ('INDEX PROD TRADING - NA', 'DSP CREDIT TDG', 'DSP INDEX PRODUCTS TRADING') THEN 'DSP INDEX PRODUCTS' ELSE  a.CCC_PRODUCT_LINE END,
    A.COB_DATE,
    A.RATING2,
    A.POSITION_ULT_ISSUER_PARTY_DARWIN_NAME