With x as (
SELECT COB_DATE,POSITION_ULT_ISSUER_PARTY_DARWIN_NAME,CCC_BUSINESS_AREA,CCC_PRODUCT_LINE,TRADE_GROUPING,CCC_PL_REPORTING_REGION,
NET_EXPOSURE,
INVENTORY,
USD_PV10_BENCH,
USD_PV01SPRD,
Coalesce(PROFILE.Beta,'Other') as BETA,
Coalesce(PROFILE.Liquidity,'Other') as LIQUIDITY,
CASE WHEN EXPOSURE.CCC_PL_REPORTING_REGION IN ('JAPAN', 'ASIA PACIFIC') THEN 'Long Term' ELSE Coalesce(Strategy,'Active Trading') END AS STRATEGY
FROM
(SELECT a.COB_DATE,    a.CCC_BUSINESS_AREA,    a.CCC_PRODUCT_LINE,    
a.CCC_PL_REPORTING_REGION,    a.POSITION_ULT_ISSUER_PARTY_DARWIN_NAME,    
    CASE WHEN substr(Book,length(Book)+1-5) = 'DISDL' THEN 'DIRECT LENDING' 
    WHEN A.PRODUCT_TYPE_CODE IN ('GVTBOND','ETF','OPTION','CRDINDEX','CDSOPTIDX','FUTURE','BOND ETF') THEN 'HEDGES'
    WHEN UPPER (A.POSITION_ULT_ISSUER_PARTY_DARWIN_NAME) 
        IN ('WASHINGTON MUTUAL PREFERRED FUNDING TRUST I', 'WASHINGTON MUTUAL, INC.', 'WASHINGTON MUTUAL PREFERRED FUNDING TRUST III'
        , 'WASHINGTON MUTUAL BANK', 'LEHMAN BROTHERS HOLDINGS INC.', 'LEHMAN BROTHERS HOLDINGS, INC.', 'LEHMAN BROTHERS HOLDINGS E-CAPITAL TRUST I'
        , 'LEHMAN BROTHERS UK CAPITAL FUNDING II LP', 'LEHMAN BROTHERS HOLDINGS CAPITAL TRUST VARIOUS SERIES', 'LEHMAN BROTHERS COMMERCIAL MORTGAGE K.K.'
        , 'LEHMAN BROTHERS JAPAN INC.', 'NORTEL NETWORKS CORPORATION', 'LANDSBANKI ISLANDS HF', 'GLITNIR BANKI HF', 'KAUPTHING BANK HF'
        , 'FONTAINEBLEAU LAS VEGAS, LLC', 'LEHMAN BROTHERS TREASURY CO. BV', 'HYPO ALPE-ADRIA-BANK INTERNATIONAL AG', 'LA SEDA DE BARCELONA SA', 'REYAL URBIS S.A.') 
        THEN 'LIQUIDATION' WHEN CCC_PL_REPORTING_REGION IN ('JAPAN', 'ASIA PACIFIC') THEN 'WORKOUT' WHEN BOOK IN ('SECTD') THEN 'WORKOUT' WHEN A.REFERENCE_ENTITY_NAME IN ('SIC PROCESSING AG', 'SOLARWORLD AG', 'Q-CELLS INTERNATIONAL FINANCE B.V.', 'CIRIO FINANZIARA SPA') THEN 'LIQUIDATION' 
        WHEN (A.POSITION_ULT_ISSUER_PARTY_DARWIN_NAME LIKE '%TRAVELPORT%' AND COB_DATE > '2015-03-25') OR PRODUCT_TYPE_CODE IN ('STOCK', 'ADR', 'EQUITY') THEN 'EQUITY'
    ELSE 'TRADING' END AS TRADE_GROUPING,
    SUM (a.USD_NET_EXPOSURE) AS NET_EXPOSURE,
    SUM (CASE WHEN a.PRODUCT_TYPE_CODE IN ('ADR', 'STOCK', 'SWAP', 'WARRNT', 'ETF', 'OPTION') THEN USD_DELTA ELSE USD_NET_EXPOSURE END) AS INVENTORY,
    SUM (A.USD_PV10_BENCH) AS USD_PV10_BENCH,
    SUM (A.USD_PV01SPRD) AS USD_PV01SPRD
FROM cdwuser.U_DM_CC a
WHERE
COB_DATE in (
'2018-02-27',
'2018-02-28')
AND    a.CCC_PRODUCT_LINE = 'DISTRESSED TRADING' AND
    a.CCC_STRATEGY <> 'PAR LOANS TRADING' AND
    a.PRODUCT_TYPE_CODE NOT IN ('GVTBOND','ETF','OPTION','CRDINDEX','CDSOPTIDX','FUTURE','BOND ETF')
GROUP BY COB_DATE,    CCC_BUSINESS_AREA,    a.CCC_PRODUCT_LINE,   
 a.CCC_PL_REPORTING_REGION,    a.POSITION_ULT_ISSUER_PARTY_DARWIN_NAME,    
    CASE WHEN substr(Book,length(Book)+1-5) = 'DISDL' THEN 'DIRECT LENDING' 
    WHEN A.PRODUCT_TYPE_CODE IN ('GVTBOND','ETF','OPTION','CRDINDEX','CDSOPTIDX','FUTURE','BOND ETF') THEN 'HEDGES' 
    WHEN UPPER (A.POSITION_ULT_ISSUER_PARTY_DARWIN_NAME) 
        IN ('WASHINGTON MUTUAL PREFERRED FUNDING TRUST I', 'WASHINGTON MUTUAL, INC.', 'WASHINGTON MUTUAL PREFERRED FUNDING TRUST III'
        , 'WASHINGTON MUTUAL BANK', 'LEHMAN BROTHERS HOLDINGS INC.', 'LEHMAN BROTHERS HOLDINGS, INC.', 'LEHMAN BROTHERS HOLDINGS E-CAPITAL TRUST I'
        , 'LEHMAN BROTHERS UK CAPITAL FUNDING II LP', 'LEHMAN BROTHERS HOLDINGS CAPITAL TRUST VARIOUS SERIES', 'LEHMAN BROTHERS COMMERCIAL MORTGAGE K.K.'
        , 'LEHMAN BROTHERS JAPAN INC.', 'NORTEL NETWORKS CORPORATION', 'LANDSBANKI ISLANDS HF', 'GLITNIR BANKI HF', 'KAUPTHING BANK HF'
        , 'FONTAINEBLEAU LAS VEGAS, LLC', 'LEHMAN BROTHERS TREASURY CO. BV', 'HYPO ALPE-ADRIA-BANK INTERNATIONAL AG', 'LA SEDA DE BARCELONA SA', 'REYAL URBIS S.A.') 
        THEN 'LIQUIDATION' WHEN CCC_PL_REPORTING_REGION IN ('JAPAN', 'ASIA PACIFIC') THEN 'WORKOUT' WHEN BOOK IN ('SECTD') THEN 'WORKOUT' WHEN A.REFERENCE_ENTITY_NAME IN ('SIC PROCESSING AG', 'SOLARWORLD AG', 'Q-CELLS INTERNATIONAL FINANCE B.V.', 'CIRIO FINANZIARA SPA') THEN 'LIQUIDATION' 
        WHEN (A.POSITION_ULT_ISSUER_PARTY_DARWIN_NAME LIKE '%TRAVELPORT%' AND COB_DATE > '2015-03-25') OR PRODUCT_TYPE_CODE IN ('STOCK', 'ADR', 'EQUITY') THEN 'EQUITY'
    ELSE 'TRADING' END
    Having SUM (CASE WHEN a.PRODUCT_TYPE_CODE IN ('ADR', 'STOCK', 'SWAP', 'WARRNT', 'ETF', 'OPTION') THEN USD_DELTA ELSE USD_NET_EXPOSURE END) is not null


) EXPOSURE

LEFT JOIN 

( select B.ATTRIBUTE1 as Issuer_Name, B.ATTRIBUTE2 as Beta, B.ATTRIBUTE3 as Strategy, B.ATTRIBUTE4 as Liquidity
from cdwuser.U_GENERIC_DATA B
where COB_DATE = (Select MAX(COB_DATE) as COB_DATE from cdwuser.U_GENERIC_DATA Where ANALYTICS = 'Corporate Credit' and ANALYTIC_GROUP = 'Distressed Trading' and COB_DATE >= '1/22/2016')
and ANALYTICS = 'Corporate Credit' and ANALYTIC_GROUP = 'Distressed Trading') PROFILE

ON EXPOSURE.POSITION_ULT_ISSUER_PARTY_DARWIN_NAME = PROFILE.Issuer_Name)

Select COB_DATE, POSITION_ULT_ISSUER_PARTY_DARWIN_NAME, CCC_BUSINESS_AREA, CCC_PRODUCT_LINE, TRADE_GROUPING, CCC_PL_REPORTING_REGION
, NET_EXPOSURE, INVENTORY, USD_PV10_BENCH, USD_PV01SPRD, BETA, LIQUIDITY, STRATEGY
from x
where Liquidity != 'Other' and Beta != 'Other'
UNION ALL
Select COB_DATE, POSITION_ULT_ISSUER_PARTY_DARWIN_NAME, CCC_BUSINESS_AREA, CCC_PRODUCT_LINE, TRADE_GROUPING, CCC_PL_REPORTING_REGION
, NET_EXPOSURE*.5 as NET_EXPOSURE, INVENTORY*.5 as INVENTORY, USD_PV10_BENCH*.5 as USD_PV10_BENCH, USD_PV01SPRD*.5 as USD_PV01SPRD, 'Low' as BETA, 'Low' as LIQUIDITY, STRATEGY
from x
where Liquidity = 'Other' and Beta = 'Other'
UNION ALL
Select COB_DATE, POSITION_ULT_ISSUER_PARTY_DARWIN_NAME, CCC_BUSINESS_AREA, CCC_PRODUCT_LINE, TRADE_GROUPING, CCC_PL_REPORTING_REGION
, NET_EXPOSURE*.5 as NET_EXPOSURE, INVENTORY*.5 as INVENTORY, USD_PV10_BENCH*.5 as USD_PV10_BENCH, USD_PV01SPRD*.5 as USD_PV01SPRD, 'Medium' as BETA, 'Medium' as LIQUIDITY, STRATEGY
from x
where Liquidity = 'Other' and Beta = 'Other'
UNION ALL
Select COB_DATE, POSITION_ULT_ISSUER_PARTY_DARWIN_NAME, CCC_BUSINESS_AREA, CCC_PRODUCT_LINE, TRADE_GROUPING, CCC_PL_REPORTING_REGION
, NET_EXPOSURE*.5 as NET_EXPOSURE, INVENTORY*.5 as INVENTORY, USD_PV10_BENCH*.5 as USD_PV10_BENCH, USD_PV01SPRD*.5 as USD_PV01SPRD, BETA, 'Low' as LIQUIDITY, STRATEGY
from x
where Liquidity = 'Other' and Beta != 'Other'
UNION ALL
Select COB_DATE, POSITION_ULT_ISSUER_PARTY_DARWIN_NAME, CCC_BUSINESS_AREA, CCC_PRODUCT_LINE, TRADE_GROUPING, CCC_PL_REPORTING_REGION
, NET_EXPOSURE*.5 as NET_EXPOSURE, INVENTORY*.5 as INVENTORY, USD_PV10_BENCH*.5 as USD_PV10_BENCH, USD_PV01SPRD*.5 as USD_PV01SPRD, BETA, 'Medium' as LIQUIDITY, STRATEGY
from x
where Liquidity = 'Other' and Beta != 'Other'
UNION ALL
Select COB_DATE, POSITION_ULT_ISSUER_PARTY_DARWIN_NAME, CCC_BUSINESS_AREA, CCC_PRODUCT_LINE, TRADE_GROUPING, CCC_PL_REPORTING_REGION
, NET_EXPOSURE*.5 as NET_EXPOSURE, INVENTORY*.5 as INVENTORY, USD_PV10_BENCH*.5 as USD_PV10_BENCH, USD_PV01SPRD*.5 as USD_PV01SPRD, 'Low' as BETA, LIQUIDITY, STRATEGY
from x
where Liquidity != 'Other' and Beta = 'Other'
UNION ALL
Select COB_DATE, POSITION_ULT_ISSUER_PARTY_DARWIN_NAME, CCC_BUSINESS_AREA, CCC_PRODUCT_LINE, TRADE_GROUPING, CCC_PL_REPORTING_REGION
, NET_EXPOSURE*.5 as NET_EXPOSURE, INVENTORY*.5 as INVENTORY, USD_PV10_BENCH*.5 as USD_PV10_BENCH, USD_PV01SPRD*.5 as USD_PV01SPRD, 'Medium' as BETA, LIQUIDITY, STRATEGY
from x
where Liquidity != 'Other' and Beta = 'Other'