with
 PRODUCT_LINE_VALUE(ccc_product_line) as ( values ('CRE LEND SECURITIZATION'),('CRE LEND - BANK HFI/HFS'),('CRE LENDING'),('CRE LENDING SEC/HFS'),('CREL BANK HFI'),('WAREHOUSE'))

SELECT
b.COB_DATE,
b.SPG_PRODUCT_TYPE,
b.CATEGORY,
sum(NET_EXPOSURE) USD_EXPOSURE,
sum(SPV01) SPV01
FROM
(

SELECT
a.COB_DATE,
a.SPG_PRODUCT_TYPE,
UNNEST(ARRAY[
CLASSIFICATION_0,
CLASSIFICATION_1,
CLASSIFICATION_2,
CLASSIFICATION_3,
CLASSIFICATION_4,
CLASSIFICATION_5,
CLASSIFICATION_6]) CATEGORY,
NET_EXPOSURE,
SPV01

FROM
(
SELECT
COB_DATE,
SPG_PRODUCT_TYPE,
Case when SPG_PRODUCT_TYPE_GROUP in ('RESI- AGENCY') then 'Agency Resi MBS' end CLASSIFICATION_0,
Case when SPG_PRODUCT_TYPE_GROUP in ('RESI- AGENCY') AND SPG_PRODUCT_TYPE in ('RESI- AGENCY POOL FIXED','RESI- AGENCY POOL ARM') then 'Agency Resi MBS Pool Only' end CLASSIFICATION_1,
Case when SPG_PRODUCT_TYPE_GROUP in ('RESI- AGENCY') AND SPG_PRODUCT_TYPE in ('RESI- AGENCY POOL FIXED', 'RESI- AGENCY POOL ARM') AND TRADE_TYPE IN ('NON-DELIVERABLE') then 'Agency Resi MBS Non-Deliverable Pool' end CLASSIFICATION_2,
Case when SPG_PRODUCT_TYPE_GROUP in ('RESI- AGENCY') AND SPG_PRODUCT_TYPE in ('RESI- AGENCY POOL ARM') AND PRODUCT_SUB_TYPE_CODE in ('FHLMC_ARM', 'FNMA_ARM', 'GNMA_ARM') then 'Agency Resi MBS Hybrid ARM' end CLASSIFICATION_3,
Case when SPG_PRODUCT_TYPE_GROUP in ('RESI- AGENCY') AND SPG_PRODUCT_TYPE LIKE 'RESI- AGENCY CMO%' then 'Agency Resi MBS CMO' end CLASSIFICATION_4,
Case when SPG_PRODUCT_TYPE_GROUP in ('RESI- AGENCY') AND SPG_PRODUCT_TYPE LIKE 'RESI- AGENCY DERIVATIVE%' then 'Agency Resi MBS Deriv' end CLASSIFICATION_5,
Case when SPG_PRODUCT_TYPE = 'AGENCY CMBS' then 'Agency CMBS' end CLASSIFICATION_6,
SUM(USD_EXPOSURE) AS NET_EXPOSURE,
SUM(USD_PV01SPRD) AS SPV01

FROM CDWUSER.U_EXP_MSR

WHERE
COB_DATE IN ('2018-02-28', '2018-02-27')
AND CCC_BUSINESS_AREA in ('SECURITIZED PRODUCTS GRP') 
AND CCC_PRODUCT_LINE NOT in (select ccc_product_line from PRODUCT_LINE_VALUE)
AND SPG_PRODUCT_TYPE_GROUP in ('RESI- AGENCY','CMBS')
AND EXP_ASSET_TYPE in ('CR','IR','OT')

GROUP BY 
COB_DATE,
SPG_PRODUCT_TYPE,
CLASSIFICATION_0,
CLASSIFICATION_1,
CLASSIFICATION_2,
CLASSIFICATION_3,
CLASSIFICATION_4,
CLASSIFICATION_5,
CLASSIFICATION_6
) A
) B

WHERE
b.CATEGORY IS NOT NULL
GROUP BY
b.COB_DATE, 
b.SPG_PRODUCT_TYPE,
b.CATEGORY