SELECT
    TAPSCUSIP,
    POSITION_ULT_ISSUER_PARTY_DARWIN_NAME,    
    COUNTRY_CD_OF_RISK,
    INSURER_RATING,
    SUM (CASE WHEN COB_DATE = '2018-02-28' then USD_EXPOSURE else 0 end) AS NET_EXPOSURE,
    ABS(SUM (CASE WHEN COB_DATE = '2018-02-28' then USD_EXPOSURE else 0 end)) AS ABS_NET_EXPOSURE,
    SUM (CASE WHEN COB_DATE = '2018-02-28' then USD_EXPOSURE else -USD_EXPOSURE end) AS NET_EXPOSURE_DOD
FROM cdwuser.U_CR_MSR a
WHERE
    a.COB_DATE IN 
    ('2018-02-28', '2018-02-27')
    AND a.CCC_BUSINESS_AREA = 'SECURITIZED PRODUCTS GRP'    
    AND CCC_PL_REPORTING_REGION = 'EMEA'
    AND spg_desc like '%RMBS%' and spg_desc not like '%AGENCY%' and CCC_PRODUCT_LINE not in ('WAREHOUSE', 'AGENCY MORTGAGE TRADING')
    AND NOT (SPG_DESC ='OTHER RMBS' or SPG_DESC like '%AGENCY%' or spg_desc like '%POOL%' or spg_desc like '%TBA%' or spg_desc like '%RMBS IOS%' or spg_desc like '%RMBS MBX%' or spg_desc like '%RMBS MBS%')
    AND COUNTRY_CD_OF_RISK IN ('PRT','IRL','ITA','GRC','ESP')
GROUP BY
    TAPSCUSIP,
    POSITION_ULT_ISSUER_PARTY_DARWIN_NAME,    
    COUNTRY_CD_OF_RISK,
    INSURER_RATING