SELECT
    A.COB_DATE,
    A.CCC_BUSINESS_AREA, 
    CASE WHEN A.GICS_LEVEL_1_NAME='GOVERNMENT' THEN 'Sov' Else 'NonSov' END AS SovFlag,
    A.PRODUCT_TYPE_CODE_GROUPED,
    SUM (A.USD_PV10_BENCH) AS USD_PV10_BENCH
FROM cdwuser.U_DM_CC A
WHERE
    A.COB_DATE IN ('2018-02-28') AND 
    A.CCC_STRATEGY = 'EM CREDIT' AND
    A.COUNTRY_CD_OF_RISK NOT IN ('ARG', 'VEN', 'UKR') 
GROUP BY
    A.COB_DATE,
    A.CCC_BUSINESS_AREA, 
    CASE WHEN A.GICS_LEVEL_1_NAME='GOVERNMENT' THEN 'Sov' Else 'NonSov' END,
    A.PRODUCT_TYPE_CODE_GROUPED