SELECT
   LE_GROUP, currency_of_measure,
    V.COB_DATE,
    v.CURRENCY_PAIR,
    v.CCC_PL_REPORTING_REGION,
    v.CCC_DIVISION,
    v.CCC_BUSINESS_AREA,
    v.PRODUCT_TYPE_CODE,



case when (v.CCC_BUSINESS_AREA IN ('CPM TRADING (MPE)','CPM', 'CREDIT', 'MS CVA MNE - FID', 'MS CVA MNE - COMMOD','COMMODS FINANCING') 
OR v.CCC_STRATEGY IN ('MS CVA MPE - DERIVATIVES', 'MS CVA MNE - DERIVATIVES')) AND v.CCC_PRODUCT_LINE NOT IN ('CREDIT LOAN PORTFOLIO', 'CMD STRUCTURED FINANCE') then 'CVA_FX_SLIDE'
when v.CCC_BUSINESS_AREA = 'LENDING' then 'LENDING'
 else 'FX_SLIDE' end as CVA_FL,
    SUM (coalesce(SLIDE_FXOPTVAR_MIN_20PCT_USD,0)) AS neg20,
    SUM (coalesce(SLIDE_FXOPTVAR_MIN_10PCT_USD,0)) AS neg10,
    SUM (coalesce(SLIDE_FXOPTVAR_MIN_05PCT_USD,0)) AS neg5,
    SUM (coalesce(SLIDE_FXOPTVAR_MIN_03PCT_USD,0)) AS neg3,
    SUM (coalesce(SLIDE_FXOPTVAR_MIN_01PCT_USD,0)) AS neg1,
    SUM (coalesce(SLIDE_FXOPTVAR_MIN_0P5PCT_USD,0)) AS neg05,
    SUM (coalesce(SLIDE_FXOPTVAR_PLS_0P5PCT_USD,0)) AS pos05,
    SUM (coalesce(SLIDE_FXOPTVAR_PLS_01PCT_USD,0)) AS pos1,
    SUM (coalesce(SLIDE_FXOPTVAR_PLS_03PCT_USD,0)) AS pos3,
    SUM (coalesce(SLIDE_FXOPTVAR_PLS_05PCT_USD,0)) AS pos5,
    SUM (coalesce(SLIDE_FXOPTVAR_PLS_10PCT_USD,0)) AS pos10,
    SUM (coalesce(SLIDE_FXOPTVAR_PLS_20PCT_USD,0)) AS pos20
FROM cdwuser.u_fx_msr V
WHERE
 COB_DATE in ('2018-02-28','2018-02-21')
    AND (v.CURRENCY_PAIR LIKE '%CN%') AND
    v.VERTICAL_SYSTEM LIKE ('FXOPT_%') AND
    (v.CURRENCY_OF_RISK_CCY1 ='CNY' OR v.CURRENCY_OF_RISK_CCY1 ='CNH') AND 
    v.CCC_DIVISION <> 'INSTITUTIONAL EQUITY DIVISION'
    AND CCC_DIVISION NOT IN ('FID DVA', 'FIC DVA')  AND CCC_STRATEGY NOT IN ('MS DVA STR NOTES IED')

GROUP BY
   LE_GROUP, currency_of_measure,
    V.COB_DATE,
    v.CURRENCY_PAIR,
    v.CCC_PL_REPORTING_REGION,
    v.CCC_DIVISION,
    v.CCC_BUSINESS_AREA,
    v.PRODUCT_TYPE_CODE,

case when (v.CCC_BUSINESS_AREA IN ('CPM TRADING (MPE)','CPM', 'CREDIT', 'MS CVA MNE - FID', 'MS CVA MNE - COMMOD','COMMODS FINANCING') 
OR v.CCC_STRATEGY IN ('MS CVA MPE - DERIVATIVES', 'MS CVA MNE - DERIVATIVES')) AND v.CCC_PRODUCT_LINE NOT IN ('CREDIT LOAN PORTFOLIO', 'CMD STRUCTURED FINANCE') then 'CVA_FX_SLIDE'
when v.CCC_BUSINESS_AREA = 'LENDING' then 'LENDING'
 else 'FX_SLIDE' end