SELECT
COB_DATE,
sum(USD_EXPOSURE) USD_EXPOSURE
from cdwuser.U_EXP_MSR
WHERE
COB_DATE IN ('2018-02-28', '2018-02-27')
AND CCC_BUSINESS_AREA in ('SECURITIZED PRODUCTS GRP') 
AND CCC_PL_REPORTING_REGION = 'AMERICAS' 
AND GICS_LEVEL_2_NAME in ('AUTOMOBILES AND COMPONENTS') 
AND PRODUCT_TYPE_CODE = 'DEFSWAP'
GROUP BY
COB_DATE