SELECT
    a.COB_DATE,
    SPG_DESC,
    a.PRODUCT_TYPE_CODE,
    CASE WHEN CCC_STRATEGY like 'EU%' then 'EU SPG'    
    WHEN CCC_STRATEGY = 'CMBS TRADING' then 'CMBS'
    WHEN CCC_STRATEGY like 'RESI%' then 'RESI'
    WHEN CCC_STRATEGY = 'ABS TRADING' then 'ABS' 
    WHEN CCC_STRATEGY like 'CLO%' then 'CLO'
    WHEN CCC_STRATEGY = 'SPG MANAGEMENT1' then 'SPG MANAGEMENT'
    else 'AGENCY' end 
    AS GROUPED_STRATEGY,
    CASE WHEN a.SPG_DESC IN ('CORPORATE INDEX', 'CORPORATE DEFAULT SWAP') AND a.CCC_PRODUCT_LINE NOT IN ('CRE LENDING', 'CREL BANK HFI', 'CRE LENDING SEC/HFS') THEN 'Corporates' 
    WHEN (SPG_DESC = 'GOVERNMENT' OR PRODUCT_TYPE_CODE in ('BERMUDAN_SWAPTION_VA','BONDFUTOPT','MISC'))  THEN 'IR Hedges - Treasury' 
    WHEN (spg_desc like 'RATE %' or spg_desc in ('SWAP','SWAPS')) THEN 'IR Hedges - Swap'    
    WHEN SPG_DESC = 'CMBS INDEX' AND a.CCC_PRODUCT_LINE IN ('SPG MANAGEMENT') THEN 'CMBX Hedge'
    WHEN SPG_DESC = 'OTHER' AND ACCOUNT IN ('07500JR18') THEN 'Resi Swap & Govt'
    ELSE 'EQUITY' END AS GROUPED_PRODUCT_TYPE,
    SUM (a.USD_IR_UNIFIED_PV01) AS PV01
FROM cdwuser.U_DM_SPG a
WHERE
    a.COB_DATE IN 
    ('2018-02-28', 
    '2018-02-27')
    AND a.CCC_BUSINESS_AREA = 'SECURITIZED PRODUCTS GRP'
    AND NOT a.CCC_PRODUCT_LINE IN ('CRE LENDING SEC/HFS', 'CREL BANK HFI', 'CRE LENDING', 'WAREHOUSE')
    AND NOT (a.SPG_DESC = 'CMBS INDEX' AND a.CCC_PRODUCT_LINE IN ('CRE LENDING SEC/HFS', 'CREL BANK HFI', 'CRE LENDING', 'SPG MANAGEMENT'))
GROUP BY
    a.COB_DATE,
    SPG_DESC,
    a.PRODUCT_TYPE_CODE,
    CASE WHEN CCC_STRATEGY like 'EU%' then 'EU SPG'    
    WHEN CCC_STRATEGY = 'CMBS TRADING' then 'CMBS'
    WHEN CCC_STRATEGY like 'RESI%' then 'RESI'
    WHEN CCC_STRATEGY = 'ABS TRADING' then 'ABS' 
    WHEN CCC_STRATEGY like 'CLO%' then 'CLO'
    WHEN CCC_STRATEGY = 'SPG MANAGEMENT1' then 'SPG MANAGEMENT'
    else 'AGENCY' end, 
    CASE WHEN a.SPG_DESC IN ('CORPORATE INDEX', 'CORPORATE DEFAULT SWAP') AND a.CCC_PRODUCT_LINE NOT IN ('CRE LENDING', 'CREL BANK HFI', 'CRE LENDING SEC/HFS') THEN 'Corporates' 
    WHEN (SPG_DESC = 'GOVERNMENT' OR PRODUCT_TYPE_CODE in ('BERMUDAN_SWAPTION_VA','BONDFUTOPT','MISC'))  THEN 'IR Hedges - Treasury' 
    WHEN (spg_desc like 'RATE %' or spg_desc in ('SWAP','SWAPS')) THEN 'IR Hedges - Swap'    
    WHEN SPG_DESC = 'CMBS INDEX' AND a.CCC_PRODUCT_LINE IN ('SPG MANAGEMENT') THEN 'CMBX Hedge'
    WHEN SPG_DESC = 'OTHER' AND ACCOUNT IN ('07500JR18') THEN 'Resi Swap & Govt'
    ELSE 'EQUITY' END