Select 
COB_DATE,  
a.CORRELATION_QUALITY,
a.VAL_DETACHMENT_POINT,
sum(a.GRID_MEASURE_VALUE) AS CORR_01  
from cdwuser.U_GRID_MSR a 
WHERE
    A.COB_DATE in ('2018-02-28','2018-01-31')
    and CCC_BUSINESS_AREA = 'DSP - CREDIT' 
    and a.GRID_MEASURE_NAME = 'USD_SENSITIVITY_SCALED' 
Group by 
COB_DATE, 
a.CORRELATION_QUALITY, 
a.VAL_DETACHMENT_POINT