SELECT
    CASE WHEN POSITION_ULT_ISSUER_PARTY_DARWIN_NAME in ('FEDERAL NATIONAL MORTGAGE ASSOCIATION','CONNECTICUT AVENUE SECURITIES') THEN 'CAS'
    else 'STACR' end as CAS_STACR,
    TAPSCUSIP,
    TRANCHE_NAME,
    VINTAGE,
    POSITION_ULT_ISSUER_PARTY_DARWIN_NAME,
    ABS(SUM (CASE WHEN COB_DATE = '2018-02-28' then USD_EXPOSURE else 0 end)) AS ABS_NET_EXPOSURE,
    SUM (CASE WHEN COB_DATE = '2018-02-28' then USD_EXPOSURE else 0 end) AS NET_EXPOSURE,
    SUM (CASE WHEN COB_DATE = '2018-02-28' then USD_PV01SPRD else 0 end) AS SPV01,
    SUM (CASE WHEN COB_DATE = '2018-02-28' then USD_IR_UNIFIED_PV01 else 0 end) AS PV01,
    SUM (CASE WHEN COB_DATE = '2018-02-28' then USD_EXPOSURE else -USD_EXPOSURE end) AS NET_EXPOSURE_DOD,
    SUM (CASE WHEN COB_DATE = '2018-02-28' then USD_PV01SPRD else -USD_PV01SPRD end) AS SPV01_DOD,
    SUM (CASE WHEN COB_DATE = '2018-02-28' then USD_IR_UNIFIED_PV01 else -USD_IR_UNIFIED_PV01 end) AS PV01_DOD
FROM cdwuser.U_EXP_MSR a
WHERE
    a.COB_DATE IN 
    ('2018-02-28', '2018-02-27')
    AND a.CCC_BUSINESS_AREA = 'SECURITIZED PRODUCTS GRP'    
    AND SPG_DESC ='RMBS CRT'
GROUP BY
    CASE WHEN POSITION_ULT_ISSUER_PARTY_DARWIN_NAME in ('FEDERAL NATIONAL MORTGAGE ASSOCIATION','CONNECTICUT AVENUE SECURITIES') THEN 'CAS'
    else 'STACR' end,
    TAPSCUSIP,
    TRANCHE_NAME,
    VINTAGE,
    POSITION_ULT_ISSUER_PARTY_DARWIN_NAME