SELECT
    A.COB_DATE,
    A.PRODUCT_TYPE_CODE_GROUPED,
    SUM (A.USD_NET_EXPOSURE) AS NET_EXPOSURE
FROM cdwuser.U_DM_CC A
WHERE
    A.COB_DATE IN ('2018-02-28') AND 
    (A.CCC_STRATEGY LIKE ('%PAR LOANS TRADING%') OR CCC_STRATEGY in ('PRIMARY LOANS - AP','SECONDARY LOANS - AP') OR A.CCC_PRODUCT_LINE = 'PAR LOANS TRADING' OR BOOK IN ('LDN PAR TRADING RG-LNRGO','LDN PAR TRADING SIDDIQUI-LNSSL'))
GROUP BY
    COB_DATE,
    A.PRODUCT_TYPE_CODE_GROUPED