SELECT
    TAPSCUSIP,
    POSITION_ULT_ISSUER_PARTY_DARWIN_NAME,
    INSURER_RATING,
    VINTAGE,
    SUM (CASE WHEN COB_DATE = '2018-02-28' then USD_EXPOSURE else 0 end) AS NET_EXPOSURE,
    ABS(SUM (CASE WHEN COB_DATE = '2018-02-28' then USD_EXPOSURE else 0 end)) AS ABS_NET_EXPOSURE,
    SUM (CASE WHEN COB_DATE = '2018-02-28' then USD_EXPOSURE else -USD_EXPOSURE end) AS NET_EXPOSURE_DOD
FROM cdwuser.U_CR_MSR a
WHERE
    a.COB_DATE IN 
    ('2018-02-28', '2018-01-31')
    AND a.CCC_BUSINESS_AREA = 'SECURITIZED PRODUCTS GRP'    
    AND NOT a.CCC_PRODUCT_LINE IN ('CRE LENDING SEC/HFS', 'CREL BANK HFI', 'CRE LENDING', 'WAREHOUSE')
    AND CCC_PL_REPORTING_REGION = 'EMEA'
    AND SPG_DESC LIKE '%CMBS%'
    AND SPG_DESC NOT IN ('CMBS INDEX', 'CMBS LOAN', 'CMBS LOAN IO')
GROUP BY
    TAPSCUSIP,
    POSITION_ULT_ISSUER_PARTY_DARWIN_NAME,
    INSURER_RATING,
    VINTAGE