SELECT
    a.PRODUCT_TYPE_CODE,
    a.COB_DATE,
    SUM (A.USD_EXPOSURE) AS USD_NET_EXPOSURE,
    SUM (A.USD_PV01SPRD) AS USD_PV01SPRD
FROM cdwuser.U_EXP_MSR A
WHERE
    a.COB_DATE IN ('2018-02-28', '2018-01-31') AND 
    a.CCC_BUSINESS_AREA = 'MUNICIPAL SECURITIES' AND
    a.PRODUCT_TYPE_CODE IN ('CRDINDEX', 'MUNICDS', 'MUNICDX')
GROUP BY
    a.COB_DATE,
    a.PRODUCT_TYPE_CODE;